server:
  port: 8084

spring:
  application:
    name: auth-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

keycloak:
  auth-server-url: http://localhost:8080
  realm: steet-app-realm
  resource: steet-app-client
  credentials:
    secret: your-client-secret
  public-client: false
  bearer-only: true
