logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG

server:
  port: 8888
spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
    gateway:
      default-filters:
        - TokenRelay
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        # Room Management Service Routes
        - id: room-service-rooms
          uri: lb://room-management
          predicates:
            - Path=/rooms/**

        - id: public-routes
          uri: lb://student-management
          predicates:
            - Path=/api/users/login,/api/users/register,/api/students/register
          filters: [ ]  # No TokenRelay filter here
          
        - id: room-service-admin
          uri: lb://room-management
          predicates:
            - Path=/roomsAdmin/**
          
        - id: private-rooms-service
          uri: lb://room-management
          predicates:
            - Path=/privateRooms/**
          
        - id: memberships-service
          uri: lb://room-management
          predicates:
            - Path=/memberships/**
          
        - id: participations-service
          uri: lb://room-management
          predicates:
            - Path=/participations/**
          
        - id: invitations-service
          uri: lb://room-management
          predicates:
            - Path=/invitations/**
          
        - id: student-rooms-service
          uri: lb://room-management
          predicates:
            - Path=/student/rooms/**
            
        # Student Management Service Routes
        - id: student-management-service
          uri: lb://student-management
          predicates:
            - Path=/api/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/steet-app-realm
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8088/realms/steet-app-realm
            token-uri: http://localhost:8088/realms/steet-app-realm/protocol/openid-connect/token
            authorization-uri: http://localhost:8088/realms/steet-app-realm/protocol/openid-connect/auth
            user-info-uri: http://localhost:8088/realms/steet-app-realm/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8088/realms/steet-app-realm/protocol/openid-connect/certs
        registration:
          steet-app-client:
            provider: keycloak
            client-id: steet-app-client
            client-secret: 9lB2zN15BGqBgfOFLiEtMiW4oZzAHGlf
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid,profile,email

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

