logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG

server:
  port: 8888
spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
    gateway:
      routes:
#        - id: graphql
#          uri: lb://gateway-service
#          predicates:
#              - Path=/graphql/**
#          filters:
#              - RewritePath=/graphql/(?<remaining>.*), /graphql/${remaining}
#        - id: STUDENT_MANAGEMENT
#          uri: lb://STUDENT_MANAGEMENT
##          uri: http://localhost:8081
#          predicates:
#            Path=/students/**
        - id: room-service
          uri: lb://ROOM-MANAGEMENT
#          uri: http://localhost:8082
          predicates:
            Path=/rooms/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true


